# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 774134c7517e9f7cadb55eb4ce7d739aa78d6b1a6fe3182997f4b83222eb1a1a9fbb12712d73768529b6041b3f59d6981efab1403f951a59db43c630fdd8362f

test:
  secret_key_base: 3227b296f3fbd933bc91105d495651d2d7b342ee327f43e2a67f55a981fcc07cf700560b91b88f78eb75a6524bc391628c5b3012e3e75bfa52cad613ec071bb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
